name: CI

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 1 * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '10'
          - '12'
          - '14'
          - '16'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npx tsc
      - name: Smoke Test
        run: |
          mkdir smoketest/
          node dist/index.js --out-dir=smoketest/
      - name: Show results of Smoke Test
        run: find smoketest/
